### PR TITLE
Fix documentation image paths following file rename

### PR DESCRIPTION
**Pull request by joncojonathan**
Following an image name tidy up by @haleilk I've updated the documentation to reflect the renamed files.

Some renamed files did not seem to feature in the documentation.  I've visually checked the documentation (every MD file) and couldn't see any broken image links.

### CODE REVIEW

**Comment by joncojonathan** [comment]
This addresses concerns in PR #8.

**Comment by ArvidNy** [comment]
Great! Do you think you would be able to change the links for the rest of the files that were renamed in this PR as well? As far as I can see, there are 13 images renamed but only 5 links that are changed.

**Comment by joncojonathan** [comment]
I noted the same but grep didn't find the other files. I'll check again in
case I made a typo!

**Comment by joncojonathan** [comment]
I did indeed miss some files, sorry @ArvidNy.  Commit 002d51cc6b3b07cd9b21fd37e005663f176c2dab should resolve everything now.  Please review.

**Comment by ArvidNy** [comment]
Great, many thanks for checking again!

**Pull request merged**
